### ISSUE TITLE
Install dependencies from a location specified in config

### ISSUE THREAD

**Issue by AndrewJohnBenjamin** [timjroberts/gulp-npmworkspace#2]
It would be great if gulp-workspace would allow the user to specify that certain npm packages should be installed from a location on disk. This would allow a project in one repositorty/project to link to packages in a seperate repository/project on their local disk that has not yet been published.

_(There is similar functionality for the mapping of registries, where a registry is supplied against a given package name to indicate that the package should be pulled from that registry)_

**Config Example**
var packageMap = {
        "my-awesome-package" : "../../packages/my-awesome-package"
    };

In the example above, whenever gulp-workspace encounters a dependency on "my-awesome-package", it would create a link to the package at the location "../../packages/my-awesome-package"

**Comment by timjroberts** [comment]
You can now include an `externalWorkspacePackageMap` option on `npmInstall()` to consider external packages:

``` javascript
var gulp = require("gulp");
var workspace = require("gulp-npmworkspace");

gulp.task("install", function() {
    return workspace.workspacePackages()
        .pipe(workspace.npmInstall({
            externalWorkspacePackageMap: {
                "my-awesome-pacakge": "../path/to/my-awesome-package"
            }
        }));
});
```
